version: "3"
services:
  web_service:
    build: filesharing-web-service
    ports:
      - "8080:8080"
    environment:
      FS_HOST: ":8080"
      FS_SESSION_EXPIRE_PERIOD_SEC: "2592000"
      FS_GATEWAY_HOST: "filesharing:8000"
    depends_on:
      - filesharing
  filesharing:
    build: .
    ports:
      - "8000:8000"
    environment:
      FS_HOST: ":8000"
      FS_FILE_SERVICE_NAME: "filesharing.fileservice"
      FS_AUTH_SERVICE_NAME: "filesharing.authservice"
      FS_SESSION_EXPIRE_PERIOD_SEC: "2592000"
      MICRO_BROKER: "nats"
      MICRO_BROKER_ADDRESS: "natsd:4222"
    depends_on:
      - file_service
      - auth_service
  file_service:
    build: filesharing-file-service
    environment:
      FS_SERVICE_NAME: "filesharing.fileservice"
      FS_ROOT_DIR: "/data/storage/"
      FS_TEMP_DIR: "/data/temp/"
      FS_PERMANENT_DIRECTORY: "permanent"
      FS_CLEAN_TIME: "23:59"
    volumes:
      - filesharing-file-service-storage:/data/
  auth_service:
    build: filesharing-auth-service
    environment:
      AS_SERVICE_NAME: "filesharing.authservice"
      AS_DB_CONNECTION_STRING: "user=postgres password=123456 dbname=filesharing host=dbpg port=5432 sslmode=disable"
      AS_TOKEN_EXPIRE_PERIOD_SEC: "2592000"
    depends_on:
      - dbpg
  telegram_bot_service:
    build: filesharing-tg-service
    environment:
      FS_SERVICE_NAME: "filesharing.tgservice"
      FS_TG_BOT_TOKEN: ""
      MICRO_BROKER: "nats"
      MICRO_BROKER_ADDRESS: "natsd:4222"
  dbpg:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: filesharing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - filesharing-db-data:/var/lib/postgresql/data/
  natsd:
    image: nats:latest
    ports:
     - 4222:4222
  # pgadmin:
  #   image: dpage/pgadmin4
  #   depends_on:
  #     - dbpg
  #   ports:
  #     - "7000:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
  #     PGADMIN_DEFAULT_PASSWORD: 123456
volumes:
  filesharing-file-service-storage:
  filesharing-db-data:
