version: "3"
services:
  web:
    build: .
    ports:
    - "8080:8080"
    environment:
      FS_HOST: ":8080"
      FS_DB_CONNECTION_STRING: "user=postgres password=123456 dbname=filesharing host=dbpg port=5432 sslmode=disable"
      FS_FILE_SERVICE_NAME: "filesharing.fileservice"
    depends_on:
    - dbpg
    - file_service
  file_service:
    build: file_service
    environment:
      FS_SERVICE_NAME: "filesharing.fileservice"
      FS_ROOT_DIR: "/data/storage/"
      FS_TEMP_DIR: "/data/temp/"
      FS_PERMANENT_DIRECTORY: "permanent"
      FS_CLEAN_TIME: "23:59"
    volumes:
    - filesharing-file-service-storage:/data/
  dbpg:
    image: postgres
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: filesharing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
    - filesharing-db-data:/var/lib/postgresql/data
volumes:
  filesharing-file-service-storage:
  filesharing-db-data:
