package main

import (
	"errors"
	"net/http"
	"os"
	"time"

	"github.com/Mikhalevich/argparser"
	"github.com/Mikhalevich/file_service/proto"
	"github.com/Mikhalevich/filesharing/handlers"
	"github.com/Mikhalevich/filesharing/router"
	"github.com/Mikhalevich/goauth"
	"github.com/Mikhalevich/goauth/db"
	"github.com/Mikhalevich/goauth/email"
	"github.com/sirupsen/logrus"
	"google.golang.org/grpc"
)

type dbParams struct {
	Host string `json:"host,omitempty"`
}

type params struct {
	Host         string   `json:"host,omitempty"`
	Title        string   `json:"title,omitempty"`
	AllowPrivate bool     `json:"allow_private,omitempty"`
	DB           dbParams `json:"db,omitempty"`
}

func newParams() *params {
	return &params{
		Host:         "",
		AllowPrivate: true,
	}
}

func loadParams() (*params, error) {
	parser := argparser.NewParser()
	host := parser.String("host", "", "listening port and hostname")

	par := newParams()
	p, err, gen := parser.Parse(par)
	if err != nil {
		return nil, err
	}

	if gen {
		return nil, errors.New("Config should be autogenerated")
	}

	par = p.(*params)

	if *host != "" {
		par.Host = *host
	}

	if par.Host == "" {
		return nil, errors.New("Invalid host name")
	}

	if par.DB.Host == "" {
		par.DB.Host = "localhost"
	}

	return par, nil
}

func main() {
	logger := logrus.New()
	logger.SetOutput(os.Stdout)
	logger.SetFormatter(&logrus.TextFormatter{
		FullTimestamp: true,
	})

	params, err := loadParams()
	if err != nil {
		logger.Error(err)
		return
	}

	storageChecker := router.NewPublicStorages()

	var auth goauth.Authentifier
	if params.AllowPrivate {
		time.Sleep(time.Second * 2)
		pg, err := db.NewPostgres(params.DB.Host)
		if err != nil {
			logger.Error(err)
			return
		}
		defer pg.Close()

		es := &email.GomailSender{
			Host:     "smtp.gmail.com",
			Port:     587,
			From:     "",
			Password: "",
		}
		auth = goauth.NewAuthentificator(pg, pg, NewCookieSession(storageChecker, 1*60*60*24*30), es)
	} else {
		auth = goauth.NewNullAuthentificator()
	}

	fsConnection, err := grpc.Dial("localhost:50051", grpc.WithInsecure())
	if err != nil {
		logger.Errorf("did not connect: %v", err)
		return
	}
	defer fsConnection.Close()
	fsClient := proto.NewFileServiceClient(fsConnection)

	h := handlers.NewHandlers(storageChecker, auth, NewGRPCFileServiceClient(fsClient), logger)
	r := router.NewRouter(params.AllowPrivate, h, logger)

	logger.Infof("Running at %s", params.Host)

	err = http.ListenAndServe(params.Host, r.Handler())
	if err != nil {
		logger.Error(err)
	}
}
