global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    metrics_path: "/metrics/"
    static_configs:
      - targets: ["filesharing:8000", "auth:8001"]