// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: history/history.proto

package history

import (
	fmt "fmt"
	_ "github.com/Mikhalevich/filesharing/proto/event"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for HistoryService service

func NewHistoryServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for HistoryService service

type HistoryService interface {
	List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error)
}

type historyService struct {
	c    client.Client
	name string
}

func NewHistoryService(name string, c client.Client) HistoryService {
	return &historyService{
		c:    c,
		name: name,
	}
}

func (c *historyService) List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error) {
	req := c.c.NewRequest(c.name, "HistoryService.List", in)
	out := new(ListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HistoryService service

type HistoryServiceHandler interface {
	List(context.Context, *ListRequest, *ListResponse) error
}

func RegisterHistoryServiceHandler(s server.Server, hdlr HistoryServiceHandler, opts ...server.HandlerOption) error {
	type historyService interface {
		List(ctx context.Context, in *ListRequest, out *ListResponse) error
	}
	type HistoryService struct {
		historyService
	}
	h := &historyServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&HistoryService{h}, opts...))
}

type historyServiceHandler struct {
	HistoryServiceHandler
}

func (h *historyServiceHandler) List(ctx context.Context, in *ListRequest, out *ListResponse) error {
	return h.HistoryServiceHandler.List(ctx, in, out)
}
